### ISSUE TITLE
Vanilla Video causing some animated images to display as a broken browser video player

### ISSUE THREAD

**Issue by butterfingersman** [AprilSylph/XKit-Rewritten#663] opened 2022-07-16 00:10 UTC
### Platform

Windows 10

### Browser

Chrome 103.0.5060.114

### Addon version

v0.20.3

### Details

Inconsistently, animated images are being turned into glitchy vanilla video players while using vanilla videos. You can click the broken video box and it shows properly in the popout that Tumblr usually gives you when you click a gif. It's about 20% of the time that I see an animated image. Turning off vanilla videos fixes the image posts.

Vanilla Videos on:
![zzz 2022-07-15_17-01-46](https://user-images.githubusercontent.com/10971749/179325945-890b9f36-3dd3-422f-ac15-1eabfe59eb3b.png)

Vanilla Videos off (no refresh):
![zzz 2022-07-15_17-02-01](https://user-images.githubusercontent.com/10971749/179325948-ec13a0b3-05da-4a70-ba2d-77700ed9ff86.png)

Top post is a working animated image, second post is not:
![zzz 2022-07-15_17-03-23](https://user-images.githubusercontent.com/10971749/179326004-52e8bec3-a5f9-49a4-9567-7689f49cadf2.png)

Clicking the broken post:
![zzz 2022-07-15_17-08-34](https://user-images.githubusercontent.com/10971749/179326245-7d83a923-541f-45c2-9be8-dd8572e66fe9.png)

[Here is a link to that working image](https://butterfingersman.tumblr.com/image/689811837732175872), and [here is a link to that non working image](https://butterfingersman.tumblr.com/image/689810976664633344).

**Comment by marcustyphoon** [comment] 2022-07-16 00:18
Duplicate of #662, but maybe we should leave this open until the next release so people see it!

(GitHub ought to add a way to close linked PRs with a release; that would be be neat.)

**Comment by butterfingersman** [comment] 2022-07-16 00:47
sorry! i searched vanilla video a few times on the issues page and didnt find it ;w;

**Comment by AprilSylph** [comment] 2022-07-16 11:17
v0.20.4 has been released and approved for Firefox. I'll close this issue when the Chrome version is approved too.

**Closed** 2022-07-18 07:07 UTC
Labels: bug
