### ISSUE TITLE
quick tags not functioning

### ISSUE THREAD

**Issue by laurellance** [AprilSylph/XKit-Rewritten#1224] opened 2023-08-18 13:09 UTC
### Platform

windows 10

### Browser

google chrome

### Addon version

v0.21.15

### Details

quick tags is not functioning. i can add new bundles or type out tags but they are not saved upon hitting enter/clicking the quick tag. text pops up saying "Uh-oh! That didn't work. Please try again." but it still does not work. have updated extension.

**Comment by marcustyphoon** [comment] 2023-08-18 13:21
Possibly caused by #965. Are you trying to add tags to a specific post? What post is it?

**Comment by laurellance** [comment] 2023-08-18 14:18
> Possibly caused by #965. Are you trying to add tags to a specific post? What post is it?

any and all posts made with the legacy editor so before NPF posts. it works fine on posts created with the beta editor as npf posts. so it does seems like this is the same issue. i apologize i am very very new to this. 

i was hoping quick tags would work with xkit rewritten because as of today my quick tags on the "new xkit" extension stopped working. it also only partially broke. i could use quick tags on published and queued posts but not on drafts which is where i need it the most.

i really don't understand much of anything. i read your concept of the problem but don't quite understand how i would implement a different api.

**Comment by marcustyphoon** [comment] 2023-08-18 14:21
Gotcha! And no worries, you've reported things perfectly!

I have a fix coded for this issue already; it just has to go through code review and get released!

**Comment by laurellance** [comment] 2023-08-18 14:27
> Gotcha! And no worries, you've reported things perfectly!

okay. phew. that's a relief. while i followed the guide on bug reporting it still felt like i did it wrong. 

ah, alright. i see. that is fantastic. if at some point it could work again. because i have far too many posts to tag and doing it manually is a nightmare. 

is there any way i can turn on notifications for the release or will it be attached as a fix to my bug report?

**Comment by marcustyphoon** [comment] 2023-08-19 02:54
Unfortunately, due to the way GitHub works, I think you can receive a notification when the fix gets merged into the main code branch, but you wouldn't also get a notification when a release is pushed to the Chrome and Firefox extension stores, or when the release passes their review (usually within a few hours for Chrome; like half a week for Firefox lately).

**Comment by laurellance** [comment] 2023-08-19 12:07
ah okay. i'll just have to keep my eye out on the chrome update once the github fix gets merged.
thank you so much for you help and explaining all of this to me. i really appreciate it. 😊

**Closed** 2023-08-20 23:31 UTC
Labels: bug
