### ISSUE TITLE
Queued items posting to Drafts

### ISSUE THREAD

**Issue by DaveKan** [AprilSylph/XKit-Rewritten#360] opened 2021-12-10 00:23 UTC
### Platform

Windows 10

### Browser

Firefox

### Addon version

0.11.1

### Details

The last few days, posts that I have added to my Queue using Quick Reblog are getting added to my Drafts at the scheduled time instead of getting posted to my timeline.

**Comment by AprilSylph** [comment] 2021-12-10 00:44
Items from your queue getting sent to drafts instead of publishing is Tumblr's behaviour for when a queued post fails to publish for any reason, and has nothing to do with Quick Reblog. [Contact Tumblr support](https://www.tumblr.com/support) if it's occurring more than usual.

duplicate of #357

**Closed by AprilSylph** 2021-12-10 00:44 UTC
Labels: bug
