### ISSUE TITLE
New posts count on TagTracking+ doesn't update properly

### ISSUE THREAD

**Issue by moonflowcr** [AprilSylph/XKit-Rewritten#1250] opened 2023-08-29 09:32 UTC
### Platform

Windows 10

### Browser

Chrome 116.0.5845.111

### Addon version

v0.22.1

### Details

I'm using the TagTracking+ feature so I can see whenever there are new posts in any of my tracked tags but I've observed something quite unusual: instead of being able to put the count to 0 by visiting the tag just once, I have to open the tag, go to a different page (dashboard, other tag, settings or any other page in the webside) and then repeat as many times if I have more than one new post.

**Comment by marcustyphoon** [comment] 2023-08-29 09:36
Duplicate of #1247!

**Closed by marcustyphoon** 2023-08-29 09:36 UTC
Labels: bug
