### ISSUE TITLE
Quick Reblog: popout stops appearing if still open during certain actions

### ISSUE THREAD

**Issue by asshuka** [AprilSylph/XKit-Rewritten#91] opened 2021-03-09 16:10 UTC
- The browser I'm using is: Firefox
- My browser version is: 86.0
- My XKit Rewritten version is:  v0.1.1
---
The QuickReblog popout sometimes stops appearing on hover altogether after certain actions on the dashboard until I refresh the page. This happens specifically if the popout is still open when: a video plays (prompted by user with Vanilla Video), or another QuickReblog popout appears. This is what I've observed so far, there might be more, but hopefully it's enough to state a pattern?

**Comment by AprilSylph** [comment] 2021-03-09 16:45
the behaviour in v0.1.1 is that the popup won't appear on another post if it's still processing the reblog of another post, which seems like it may get stuck if the post fails to reblog for any reason since there isn't much error handling done there. i'm currently revamping how the popout works to remove these conditions and add error handling to reblogging posts, so maybe that will fix this issue.

i'll follow up on this with you when i release these changes in v0.2.0!

**Comment by AprilSylph** [comment] 2021-03-12 14:55
@asshuka v0.2.0 just released with some changes to Quick Reblog that i mentioned; the popup should now always be able to move between posts, but the action buttons (reblog, queue, draft) will be unavailable if it's still currently processing a post. please let me know if you can still reproduce this bug, or close this issue if you can't.

**Closed** 2021-03-12 18:26 UTC
Labels: bug
