### ISSUE TITLE
No Recommended Blogs & Radar not hidden

### ISSUE THREAD

**Issue by cynanthropy** [AprilSylph/XKit-Rewritten#1321] opened 2023-10-31 07:47 UTC
### Platform

Linux (Debian 12)

### Browser

Firefox 115.3.0esr

### Addon version

0.23.0beta

### Details

Some of the No Recommended options don't seem to be working, I still have the recommended blogs section and the tumblr radar section. Have reinstalled and no change.

**Comment by AprilSylph** [comment] 2023-10-31 07:48
Duplicate of #1316.

**Closed by AprilSylph** 2023-10-31 07:48 UTC
Labels: bug
