### ISSUE TITLE
No recommended not hiding recommended blogs in the middle of the dashboard.

### ISSUE THREAD

**Issue by stellayurigasaki** [AprilSylph/XKit-Rewritten#1227] opened 2023-08-21 00:36 UTC
### Platform

Windows 10

### Browser

Google Chrome Version 116.0.5845.97 

### Addon version

0.21.15

### Details

Recently tumblr implemented a new feature that recommends blogs in the middle of your dashboard. I have tried to hide it via the no recommended feature and it did not work. I  uninstalled my old xkit (that I currently use only for its blacklist) to see if that solved the issue but it did not work. [Attached is an image of the issue.](https://imgur.com/a/WHFpPc8) Thank you!

**Comment by marcustyphoon** [comment] 2023-08-21 00:38
Duplicate of #1195, which you understandably would have not seen because a fix was implemented already and will be out in the next release!

**Closed by marcustyphoon** 2023-08-21 00:38 UTC
Labels: bug
