### ISSUE TITLE
Featured posts and ads getting through No Recommended

### ISSUE THREAD

**Issue by luxidoptera** [AprilSylph/XKit-Rewritten#330] opened 2021-11-10 18:50 UTC
### Platform

Windows 10

### Browser

4.3.2439.65 (Stable channel) (32-bit)

### Addon version

v0.9.2

### Details

The addon No Recommended currently fails to catch "featured" posts, the "moat" at the top of the dashboard, and any and all ads (which are also not currently caught by ublock origin, though that isn't your problem). While I know ads are technically not part of the feature set for No Recommended, I felt it was still worth noting.

Below are relevant screenshots; one of a featured post, another of my uBlock Origin filters made in a desperate attempt to get this junk off my dashboard.

![image](https://user-images.githubusercontent.com/15697751/141174719-29a411ac-f416-4072-b530-3087fe035d41.png)
![image](https://user-images.githubusercontent.com/15697751/141174786-6b3535a0-270a-4749-9dae-2499e12a048a.png)

**Comment by AprilSylph** [comment] 2021-11-10 20:56
Duplicate of #303

**Closed by AprilSylph** 2021-11-10 20:56 UTC
Labels: bug
