### ISSUE TITLE
Tag Tracking+ No longer updates unread tag count

### ISSUE THREAD

**Issue by Echoweaver** [AprilSylph/XKit-Rewritten#849] opened 2022-11-20 23:24 UTC
### Platform

MacOS 10.15.7 (Catalina)

### Browser

Firefox 107.0

### Addon version

0.21.0

### Details

I've been checking reported issues to see if this is widespread, and nobody seems to be reporting it. I suppose I'd guess it might be related to my non-Windows, non-Chrome setup.

Since the update that added the Tag Tracking+ sidebar (which I love in theory), none of my tracked tags update to their unread post count.

**Comment by AprilSylph** [comment] 2022-11-20 23:39
Duplicate of #846?

**Closed by AprilSylph** 2022-11-20 23:39 UTC
Labels: bug, duplicate

**Comment by Echoweaver** [comment] 2022-11-20 23:54
Crud. My browser indicated I did not submit this, so I submitted the other one. Whoops.
