### ISSUE TITLE
Tweaks option to remove the Changes/Shop/etc. links leaves an orphaned element behind

### ISSUE THREAD

**Issue by ketsuban** [AprilSylph/XKit-Rewritten#1198] opened 2023-08-15 23:27 UTC
### Platform

Windows 11

### Browser

Firefox 116

### Addon version

v0.21.14

### Details

Enabling the Tweaks option "Turn the Changes/Shop/etc. links into a separating line" fails to remove the randomly-selected heading ("Content for the content gods", "Check these out", "Roll the dice", etc.) which is left orphaned.

**Comment by marcustyphoon** [comment] 2023-08-16 00:48
duplicate of #1195!

**Closed by marcustyphoon** 2023-08-16 00:48 UTC
Labels: bug
