### ISSUE TITLE
Mutual checker doesn't work on dashboard

### ISSUE THREAD

**Issue by roryrara** [AprilSylph/XKit-Rewritten#1141] opened 2023-07-12 23:31 UTC
### Platform

Windows 10

### Browser

Firefox 115.0.2 (64-bit)

### Addon version

7.9.2

### Details

Mutual Checker doesn't show an icon in front of the poster's username

**Comment by AprilSylph** [comment] 2023-07-12 23:40
7.9.2 is a New XKit version. Also, this is a duplicate of #1138.

**Closed by AprilSylph** 2023-07-12 23:40 UTC
Labels: bug

**Comment by roryrara** [comment] 2023-07-13 00:01
My bad, I meant for the Rewritten, will it be fixed?

**Comment by marcustyphoon** [comment] 2023-07-13 12:04
It already is; you will get v0.21.13 automatically once it goes through Mozilla's review process!
