### ISSUE TITLE
Quick Tags "Uh-oh! That didn't work. Please try again."

### ISSUE THREAD

**Issue by fallslikeicarus** [AprilSylph/XKit-Rewritten#411] opened 2022-01-25 13:22 UTC
### Platform

Windows 10

### Browser

Firefox 96.0.2 (64-bit)

### Addon version

v0.14.02

### Details

Quick Tags work when adding tags to my own post on Dash, Drafts, and Queue but show up error message when adding tags to posts in blog view, both in blog/[url] and blog/view/[url] show up errors.

**Comment by AprilSylph** [comment] 2022-01-25 13:24
What error message is it? And, does it persist after performing a full page reload?

**Comment by fallslikeicarus** [comment] 2022-01-25 13:26
> 

'Uh oh! That didn't work. Please try again'. it still persists after full reload, but it doesn't work on Dash or Queue either

**Comment by AprilSylph** [comment] 2022-01-25 13:26
Unable to reproduce on Firefox 96.0.2 (64-bit) using XKit Rewritten v0.14.2

**Comment by AprilSylph** [comment] 2022-01-25 13:30
It appears this only happens for some posts. I'm able to reproduce the issue only with one post in my drafts.

**Comment by fallslikeicarus** [comment] 2022-01-25 13:33
Poking around a bit, and right now quick tags are working on text posts, but not on photo posts

**Comment by AprilSylph** [comment] 2022-01-25 13:43
This only happens on legacy media posts. For some reason, Tumblr is now unable to accept NPF edits to legacy posts unless they're text posts... but does not convert those text posts to NPF.

**Comment by fallslikeicarus** [comment] 2022-01-25 13:49
How old are 'legacy media' posts? I have a post on my blog originally posted 6 days ago that also throws up the error

**Comment by AprilSylph** [comment] 2022-01-25 13:51
Anything posted from the non-beta web editor is legacy.

**Comment by AprilSylph** [comment] 2022-01-25 18:02
According to https://github.com/AprilSylph/XKit-Rewritten/discussions/410#discussioncomment-2044575, it is expected that editing legacy posts with NPF endpoints will fail. NPF posts and NPF reblogs of legacy posts should continue to be editable.

**Comment by AprilSylph** [comment] 2023-02-12 00:01
Closing as retroactive duplicate of #965

**Closed by AprilSylph** 2023-02-12 00:01 UTC
Labels: bug, wontfix
