### ISSUE TITLE
Quick Reblog stuck on processing

### ISSUE THREAD

**Issue by petroplant** [AprilSylph/XKit-Rewritten#420] opened 2022-01-27 02:03 UTC
### Platform

Chrome OS 14092

### Browser

Chrome 93

### Addon version

0.14.1

### Details

whenever i try to use the quick reblog function (queue or just reblog), it gets stuck on the processing message and doesn't change, and it prevents me from reblogging any other posts as well.

**Comment by marcustyphoon** [comment] 2022-01-27 02:06
Duplicate of #409 - make your browser update to 0.14.2 for this fix!

**Closed by marcustyphoon** 2022-01-27 02:06 UTC
Labels: bug
