### ISSUE TITLE
Soft Block/Mute User

### ISSUE THREAD

**Issue by angelinezhang21** [AprilSylph/XKit-Rewritten#1157] opened 2023-07-21 01:55 UTC
### Concept

similar to twitter's "mute" function where any post from the user would be hidden from you even if it is reblogged onto dash, accomplished without blocking the user.

**Comment by marcustyphoon** [comment] 2023-07-21 06:13
Duplicate of #674!

**Closed** 2023-07-21 06:14 UTC
Labels: enhancement
