### ISSUE TITLE
Quick Reblog not highlighting queued and drafted posts

### ISSUE THREAD

**Issue by asshuka** [AprilSylph/XKit-Rewritten#105] opened 2021-03-22 09:12 UTC
- The browser I'm using is: Firefox
- My browser version is: 86.0.1
- My XKit Rewritten version is: 0.2.3
---
Like https://github.com/AprilSylph/XKit-Rewritten/issues/95 but this time it only affects queued and drafted posts it seems. Now all posts including the first one of the page are not highlighted.

**Comment by AprilSylph** [comment] 2021-03-22 17:14
it should now be impossible for Quick Reblog to overwrite its own storage as of v0.2.2... are you using it in multiple tabs at the same time?

**Comment by asshuka** [comment] 2021-03-22 17:20
Nope! I did a quick test just now and the problem persists. I noticed this started about a day and a half or so ago, so maybe it's a Tumblr update that caused it?

**Comment by AprilSylph** [comment] 2021-03-22 17:30
if it is somehow a tumblr update, it's not one that i've received.

since i can't reproduce this issue, i have no hope of fixing it, sorry.

**Comment by asshuka** [comment] 2021-03-24 20:13
I've done a little more testing with all other extensions except Xkit Rewritten turned off, the problem still persists so at least I'm sure it's not an extension conflict on my end. I cycled through Tumblr's dashboard themes, so I'm also sure it's not them causing this. I'm not sure how helpful this information this, if there's anything else I can do to locate the cause please do let me know :x 
Unfortunate I've also found another problem with the post highlighting: when I went to view my posts through /blog not all posts are highlighted, including ones I just reblogged (without drafting or queuing) minutes ago, so they're not out of range of what QR can remember.

Other information I can provide for my specific browser instance, again not sure how much it could help:
- I have my Firefox set to delete cache and history (but not cookies so I'm not logged out of websites by this) everytime it's closed (but the QR problem occurs by navigating out of the page so I'm not sure if this relates)
![210325_03-08-18](https://user-images.githubusercontent.com/80346620/112376785-744e8800-8d17-11eb-8145-9ed5852df419.png)
- I'm using a custom stylesheet for Firefox
![210325_03-10-53](https://user-images.githubusercontent.com/80346620/112376997-c5f71280-8d17-11eb-9683-d4cbe4cd83b3.png)

Attaching my XKit pref file (again with .txt stuck to it) if it helps in any way
[XKit Payload 1616615576509.json.txt](https://github.com/AprilSylph/XKit-Rewritten/files/6200197/XKit.Payload.1616615576509.json.txt)

**Comment by AprilSylph** [comment] 2021-03-24 22:16
on posts you expect to be marked as reblogged, can you check the original post's ID and see if it's in your `quick_reblog.alreadyRebloggedList` or not? i see that the list in your backup is fairly populated, so any posts matching any of those root IDs should be marked as reblogged

**Comment by asshuka** [comment] 2021-03-24 22:22
I checked several posts and they weren't in the list :o

**Comment by AprilSylph** [comment] 2021-03-24 22:31
alright... just to be absolutely sure that this isn't a tumblr update, of those posts which root IDs were missing from the list, are the direct parent post (the specific reblogs that you reblogged from) IDs also missing, or are they present?

**Comment by asshuka** [comment] 2021-03-24 22:32
They're also not there.

**Comment by AprilSylph** [comment] 2021-03-24 22:40
okay, good, so the problem is simply that the reblogs aren't being registered in the first place, rather than the wrong ID being registered. this at least rules one fault out, but i'm not sure how a post root ID can be outright discarded given that the entire script now only has one `StorageArea.set()` call, and it's in a function which cannot be called until any previous calls to it are finished, barring using Quick Reblog in multiple tabs to evade this restriction.

the only possibility i can think of here is that you're expecting Quick Reblog to remember reblogs made through other methods (such as Tumblr's fast reblog shortcuts, or the full reblog editor window)... which it did initially attempt to do, but couldn't be done in a way that was free of the race condition which caused #95.

**Comment by asshuka** [comment] 2021-03-24 22:43
Unfortunately no, I reblog exclusively using QR save for the rare Radar posts :(

**Comment by AprilSylph** [comment] 2021-03-24 22:56
in that case, i can only assume that the storage setter call is failing for reasons i can't think of. it's late for me now, but tomorrow i'll create a debug package for you and upload it here.

**Comment by AprilSylph** [comment] 2021-03-25 17:12
(you might want to save your current config to file before doing any of this, just in case)

[xkit_rewritten-0.2.5.zip](https://github.com/AprilSylph/XKit-Rewritten/files/6206413/xkit_rewritten-0.2.5.zip)

here's the debug package. here's how to use it:
1. download the package
2. navigate to `about:addons` and disable the release version of XKit Rewritten
3. navigate to `about:debugging#/runtime/this-firefox` and click "Load Temporary Add-on…", then open the zip from the prompt
4. activate Quick Reblog in the debug version
5. perform a browser refresh on any Tumblr tabs you have open (ideally, only use one for this test)
6. use `CTRL`+`SHIFT`+`I` to open Firefox's devtools on your Tumblr tab, then open the Console tab in it
7. ensure Errors and Debug are selected (ideally, deselect everything else too)
8. reblog a post not marked as reblogged via Quick Reblog

after you get the browser notification for successful posting, the console should either say the root ID was successfully saved (and then spit out the new full list of saved IDs for good measure), or give some kind of error log highlighted in red.

for successes, make sure it was truly a success by
1. comparing the success message with the list; the new ID should be the last item in the array
2. comparing the list in the console with the data shown in the Backup tab; if they don't match, something seriously funky is up

and for errors, copy the whole thing (right-click -> "Copy message") and paste it as a comment here.

when you're done, switch back to the `about:debugging` tab and remove the debug version there to make sure you're uninstalling the right one, then re-enable the release version of XKit Rewritten from `about:addons`.

**Comment by asshuka** [comment] 2021-03-26 03:34
Sorry for the late response! I've done as instructed, and tried to reblog 8 posts, however the quick_reblog.alreadyRebloggedList only logged 5. I noticed that there was no notification popup for the posts that weren't logged, but they were successfully reblogged. There was no error log by XKit though, the posts were simply not registered.
Here's the whole console report at the last instance (after a refresh to make sure that the unlogged posts were truly not highlighted)

```
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. main-d5259e38.js:1:151178
Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src"). onloadwff.js:71:790981
Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src"). inject.js:22:29
Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src"). inject.js:41:35
POSThttps://www.tumblr.com/svc/cspreports
[HTTP/2 400 Bad Request 914ms]

Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src"). inject.js:22:29
Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src"). inject.js:41:35
POSThttps://www.tumblr.com/svc/cspreports
[HTTP/2 400 Bad Request 960ms]

Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src"). onloadwff.js:71:790981
Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src"). inject.js:22:29
Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src"). inject.js:41:35
Successfully saved quick_reblog.alreadyRebloggedList with new rootID 646687093348859904 quick_reblog.js:129:23
Array(3) [ "154084463147", "72462411155", "646687093348859904" ]
quick_reblog.js:130:23
Successfully saved quick_reblog.alreadyRebloggedList with new rootID 617216739044950016 quick_reblog.js:129:23
Array(4) [ "154084463147", "72462411155", "646687093348859904", "617216739044950016" ]
quick_reblog.js:130:23
Successfully saved quick_reblog.alreadyRebloggedList with new rootID 646148794115866624 quick_reblog.js:129:23
Array(5) [ "154084463147", "72462411155", "646687093348859904", "617216739044950016", "646148794115866624" ]
```

**Comment by AprilSylph** [comment] 2021-03-26 03:43
ah, i think i see the problem! if it's not even getting to send success notifications, there's one line of code which could cause the entire flow to error out, specifically if the Quick Reblog prompt isn't visible at the time that the reblog request is finished. i wasn't able to reproduce it because those network requests take less time for me than i'm able to make the prompt disappear! i'll fix this tomorrow, and hopefully this is the last thing standing between you and Quick Reblog remembering everything it's supposed to.

**Comment by AprilSylph** [comment] 2021-03-26 03:45
https://github.com/AprilSylph/XKit-Rewritten/blob/master/src/scripts/quick_reblog.js#L107
```diff
- if (lastPostID === null) {
+ if (lastPostID === null && popupElement.parentNode) {

**Closed** 2021-03-26 16:28 UTC
Labels: bug
