### ISSUE TITLE
Quick Reblog Not Working

### ISSUE THREAD

**Issue by katyggls** [AprilSylph/XKit-Rewritten#408] opened 2022-01-25 12:23 UTC
### Platform

Windows 10

### Browser

Microsoft Edge

### Addon version

Beta 0.14.1

### Details

As of this morning Quick Reblog is no longer working for me. When I try to reblog, queue, or save a draft from the little popup menu it just says "Processing" but it never resolves and the post never gets reblogged. I've tried uninstalling xkit rewritten and reinstalling, and issue persists. I've attached a screenshot.

![quckreblogbroken](https://user-images.githubusercontent.com/13756649/150976009-a3372696-280d-42fa-9002-a45760d25aa0.png)

**Comment by akunohomu** [comment] 2022-01-25 12:25
Same issue, Chrome 97. From briefly looking at dev tools it doesn't look like XKit's making a network request at all.

**Comment by AprilSylph** [comment] 2022-01-25 12:25
This is caused by Tumblr updating... something, about React, which makes everything fail to find React properties.

This affects most things, but is easy enough to fix. I'll keep this issue open until v0.14.2 is released to all stores.

**Comment by AprilSylph** [comment] 2022-01-25 12:27
actually, closing in favour of #409, which is more descriptive

**Closed by AprilSylph** 2022-01-25 12:27 UTC
Labels: bug
