### ISSUE TITLE
Tag Replacer only replacing 5 posts at a time

### ISSUE THREAD

**Issue by the-graves-family** [AprilSylph/XKit-Rewritten#673] opened 2022-07-25 08:00 UTC
### Platform

Windows 10

### Browser

Chrome 103.0.5060.134 and Firefox 102.0.1

### Addon version

v.0.20.4 (Beta)

### Details

Hello! 

When using the Tag Replacer, it says it finds all the posts with the tag I'm trying to replace (say about 78 posts), and then, it says it's replaced all of them with the new tag. But I went and did it again, just to check, and found out it only replaced five of the posts. Every time I did it again, it replaced five posts. Reloading, logging out, restarting did nothing, nor did changing into Firefox. This happened both with tags that had a lots of posts (over 1000) and tags that had like, 20 posts.

I could use some help, even if just to know if it's a 'me' thing, or something that's happened to several people.

(I'm very very new to both XKit and GitHub, so I'm sorry if there's anything wrong or missing from this.)

**Comment by AprilSylph** [comment] 2022-07-25 12:46
Strange, not sure what could be causing this. The Mass Post Editor endpoints should be adding and then removing tags in batches of 100. Maybe the post IDs are getting mangled somewhere...

Can you add or remove tags successfully on more than 5 posts at a time via the actual Mass Post Editor? This could be a Tumblr bug.

**Comment by the-graves-family** [comment] 2022-07-26 06:34
I just checked, and I can both add and remove tags via the Mass Post Editor on more than 5 posts. Still no luck on the Tag Replacer, though.

**Comment by marcustyphoon** [comment] 2022-07-26 08:52
Was it always the first (or last) five posts that were edited, or a random selection of five? Five seems like such a specific number!

**Comment by the-graves-family** [comment] 2022-07-26 18:28
Well, it's actually weirder now. I was away from my PC all day and tried replacing tags again to take screenshots to put here and, I don't even know what it's doing anymore. It doesn't find the same number of posts it replaces, and it keeps not replacing everything. I'm really at a loss. (I'm not sure if the screenshots will work, but they were taken in order they appeared.)

![replace1](https://user-images.githubusercontent.com/109947823/181083391-cb5f6905-1a5f-4014-995d-f3a80ec5a7ff.JPG)
![replace2](https://user-images.githubusercontent.com/109947823/181083385-850e86b6-568f-4cfa-b0b0-b193a17d769d.JPG)
![replace3](https://user-images.githubusercontent.com/109947823/181083379-9e4b6e8b-fdf6-4fa8-ab65-ce9a573190fc.JPG)
![replace4](https://user-images.githubusercontent.com/109947823/181083390-9c81c28a-2fca-4702-96f0-f4f90a408979.JPG)

**Comment by AprilSylph** [comment] 2022-07-26 22:05
So, what's (probably) happening here is: there's a single API call to grab just the number of posts in the tag. This is something the Tumblr API exposes as separate information from the posts themselves. I built this in just as a quick sanity check of "does this tag actually have posts in it? if not, exit. otherwise, display the number." But the API is no longer responding with just posts, but also ads amongst them.

It makes perfect sense to me that a tag with 103 actual posts would have 106 total objects, since we fetch posts in batches of 50 (the maximum amount allowed), which would make for 3 API requests, which assuming 1 ad per API response, gives us 3 ads.

#675 aims to filter the ads out of the responses. Hopefully that's the cause of the editing issue too.

**Comment by AprilSylph** [comment] 2022-07-30 19:12
@the-graves-family XKit Rewritten **v0.20.5** has been released with a potential fix, when you get it (might be a few days since Google take their sweet time to "review" extension updates), please let us know if this issue is resolved.

**Comment by the-graves-family** [comment] 2022-07-31 23:21
Sorry for taking so long to respond! I'll let you know immediately when I update and try again, to see if it's solved.

**Comment by the-graves-family** [comment] 2022-07-31 23:57
Update! Chrome still hasn't updated, but I tried it on Firefox, and it worked! It replaced all the tags (even the ones that were like 500 posts), and had no more problems. Thank you so much for all your help!

**Comment by AprilSylph** [comment] 2022-08-01 07:08
resolved by #675

**Closed by AprilSylph** 2022-08-01 07:08 UTC
Labels: bug
