### ISSUE TITLE
Tag Tracking+ new post counts not clearing correctly when page is visited

### ISSUE THREAD

**Issue by lihatt** [AprilSylph/XKit-Rewritten#1281] opened 2023-09-13 21:46 UTC
### Platform

Windows 10

### Browser

Firefox 117.0.1 (64 bit)

### Addon version

v0.22.1

### Details

I noticed this behavior beginning in the past week or so. Previously, when I visited the tag page for one of my tracked tags, this would always cause Tag Tracking+ to immediately clear its count of how many new posts were in the tag. I thought at first that it was now failing to clear them at all, but that's not quite it; rather it's behaving inconsistently. 

_Usually_ it appears to be decrementing the count by 1 when I load the tag page; very rarely when the number is 2+ it does actually clear it (I've seen it happen, haven't been able to reliably reproduce) but normally not. If I refresh the tag page repeatedly I can then usually watch it count down one at a time until finally the tag disappears from the list - and when I say "watch", I mean that I can actually see Xkit change the number after/during the page load (e.g. it loads with 4, and then I see it rewrite 3 instead). On some occasions when I visit the tag page the number neither clears nor decrements but I can't reliably reproduce that either, so far.

Loading the tag within the same page (i.e. left-click on the sidebar or search dropdown item) vs opening a new tab (middle-click, my usual practice to open all the tags with new posts all at once) doesn't seem to have any consistent effect; they're both squirrelly in the way I've described. 

The counts seem to be otherwise accurate (displaying 1-7+ and only showing new posts when there truly are), it's just a hassle to clear the count down to 0 each time. (Fortunately I don't follow any really, really posty tags!)

**Comment by marcustyphoon** [comment] 2023-09-13 21:48
Duplicate of #1247! This should be fixed in v0.22, which has just been released for Firefox!

**Closed by marcustyphoon** 2023-09-13 21:48 UTC
Labels: bug

**Comment by lihatt** [comment] 2023-09-13 22:07
Oh geez, sorry. I did look for open issues re: Tag Tracking+ but didn't look at the closed ones. Derp.
